import manifest from './manifest.json';
import { LEVELS, type Level } from './types';

export interface BatchInfo {
  file: string;
  from: number;
  to: number;
  count: number;
  levels: Partial<Record<Level, number>>;
}

/** Generated by scripts/validate-words.ts: one row per batch file in src/content/words. */
export const MANIFEST: readonly BatchInfo[] = manifest as BatchInfo[];

/** How many words of each level exist in the base, shown on the Setup screen (SPEC §3). */
export const LEVEL_COUNTS: Record<Level, number> = Object.fromEntries(
  LEVELS.map((level) => [level, MANIFEST.reduce((n, b) => n + (b.levels[level] ?? 0), 0)]),
) as Record<Level, number>;
